name: Foo

on:
  pull_request:
    types: ['*']
    branches:
      - 'main'

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:

      - if: ${{ !contains(github.event.pull_request.title, 'MAIN') }}
        run: |
          echo 'PR base branch is MAIN and PR title does not contain the word'
          exit 1
    
