name: Foo

on:
  pull_request:
    types: ['*']
    branches:
      - '**'

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:

      - if: ${{ contains(github.event.pull_request.base.ref, 'main') && !contains(github.event.pull_request.title, 'main') }}
        run: |
          echo 'PR base branch is MAIN and PR title does not contain the word'
          echo 'REF ${{ github.event.pull_request.base.ref }}'
          exit 1
    
